### ISSUE TITLE
Description of Nomination Java Object

### ISSUE THREAD

**Issue by lewismc** [socrata/soda-java#12]
Hi Folks,
I recently picked up the soda-java API and am in the process of coding but I am unsure as to the definition of the 'Nomination' object.
An example of it's use is as follows
```
List<Nomination> nominations = consumer.query("nominationsCopy",
                                              SoqlQuery.SELECT_ALL,
                                              Nomination.LIST_TYPE);
```
with the object being ```List<Nomination>```. Can someone help me understand this please? I can't find the class in the Javadoc.
Thanks in advance for any info.

**Comment by lewismc** [comment]
OK I found it within the test suite for the API!

**Comment by chrismetcalf** [comment]
Sorry I missed this one @lewismc, and I'm glad you figured it out on your own!

**Comment by lewismc** [comment]
hi @chrismetcalf I wonder if you can provide details on how I can get an article into the Socrata developer blog? I'm about to post a patch for a [protocol-soda-consumer](https://issues.apache.org/jira/browse/NUTCH-2185) in [Apache Nutch](http://nutch.apache.org) meaning that you can now crawl data contained within any Socrata portal. Would be really nice to open this up and make others aware that the functionality is available. I'll be announcing it over in the Nutch community but it would be great if a blog post could accompany.
