### ISSUE TITLE
when is the next release?

### ISSUE THREAD

**Issue by bowenli86** [socrata/soda-java#26]
Hi guys, 
    when is the next release? I'm looking forward to the upgrading of jackson 2

**Comment by chrismetcalf** [comment]
@bowenli86 Are you pulling from Maven or from GitHub Releases? I can get a JAR up in GH pretty soon.

**Comment by bowenli86** [comment]
Hi Chris, I'm pulling from Maven. Get a new release to Maven would be great! Thanks

**Comment by chrismetcalf** [comment]
@bowenli86: @rjmac was nice enough to help kick off the Maven upload, and the final PR is going through its unit testing now: https://github.com/socrata/soda-java/pull/30

You should see the `0.9.13` release show up in Maven very soon: https://mvnrepository.com/artifact/com.socrata/soda-api-java

**Comment by chrismetcalf** [comment]
https://mvnrepository.com/artifact/com.socrata/soda-api-java/0.9.13 🍺
