### ISSUE TITLE
com.socrata.exceptions.QueryTooComplexException: Only simple comparison filters are allowed

### ISSUE THREAD

**Issue by hdattada** [socrata/soda-java#7]
I am trying to add where clause to calculate distance between 2 points and it gives me the above error.

This is QueryBuilder expression:

		query = new SoqlQueryBuilder().
				addSelectPhrase("drv_prty_trap_ind").
				addSelectPhrase("drv_pos_cd").
				addSelectPhrase("drv_crsh_id").
				addSelectPhrase("drv_unit_num").
				addSelectPhrase("drv_prty_age").
				addSelectPhrase("drv_rstr_use_cd").
				addSelectPhrase("drv_injy_svty_cd").
				addSelectPhrase("drv_ab_depl_cd").
				addSelectPhrase("drv_prty_ejct_ind").
				addSelectPhrase("drv_hzrd_actn_cd").	
				addSelectPhrase("drv_alch_susp_ind").
				addSelectPhrase("drv_drug_susp_ind").
				addSelectPhrase("drv_hzrd_citn_ind").
				addSelectPhrase("drv_date_val").
				addSelectPhrase("drv_milt_time").
				addSelectPhrase("location_1").
				setWhereClause("DISTANCE(location_1, GEOLOCATION(37.775,-122.418), 'mi') < 5").
				build();

**Comment by znep** [comment]
Hi there,

Sorry for the greatly delayed response and I know this response probably isn't useful to you any more but I ran across this and wanted to make sure it was answered.

The issue with your query is that the `distance` / `geolocation` syntax you are using isn't for a Socrata API.  You can find an example of syntax that will work at https://dev.socrata.com/docs/functions/within_circle.html although note that requires meters.

Sorry for the delayed response, hope you managed to solve your problem already.
